#ifndef __ARCH_MSM_BOARD_M3_H
#define __ARCH_MSM_BOARD_M3_H

enum {
	GPIO_EXPANDER_IRQ_BASE	= NR_MSM_IRQS + NR_GPIO_IRQS,
	GPIO_EXPANDER_GPIO_BASE	= NR_MSM_GPIOS,
	/* SURF expander */
	GPIO_SURF_EXPANDER_BASE	= GPIO_EXPANDER_GPIO_BASE,
	GPIO_BT_SYS_REST_EN	= GPIO_SURF_EXPANDER_BASE,
	GPIO_WLAN_EXT_POR_N,
	GPIO_DISPLAY_PWR_EN,
	GPIO_BACKLIGHT_EN,
	GPIO_PRESSURE_XCLR,
	GPIO_VREG_S3_EXP,
	GPIO_UBM2M_PWRDWN,
	GPIO_ETM_MODE_CS_N,
	GPIO_HOST_VBUS_EN,
	GPIO_SPI_MOSI,
	GPIO_SPI_MISO,
	GPIO_SPI_CLK,
	GPIO_SPI_CS0_N,
	GPIO_SURF_EXPANDER_IO13,
	GPIO_SURF_EXPANDER_IO14,
	GPIO_SURF_EXPANDER_IO15,
	/* Camera expander on SURF */
	GPIO_SURF_CAM_EXPANDER_BASE	= GPIO_SURF_EXPANDER_BASE + 16,
	GPIO_SURF_CAM_GP_STROBE_READY	= GPIO_SURF_CAM_EXPANDER_BASE,
	GPIO_SURF_CAM_GP_AFBUSY,
	GPIO_SURF_CAM_GP_CAM_PWDN,
	GPIO_SURF_CAM_GP_CAM1MP_XCLR,
	GPIO_SURF_CAM_GP_CAMIF_RESET_N,
	GPIO_SURF_CAM_GP_STROBE_CE,
	GPIO_SURF_CAM_GP_LED_EN1,
	GPIO_SURF_CAM_GP_LED_EN2,
	/* FFA expander */
	GPIO_FFA_EXPANDER_BASE	= GPIO_SURF_CAM_EXPANDER_BASE + 8,
	GPIO_FFA_BT_SYS_REST_EN	= GPIO_FFA_EXPANDER_BASE,
	GPIO_FFA_WLAN_EXT_POR_N,
	GPIO_FFA_LCD_PWR_EN_N,
	GPIO_FFA_GPIO_EXP_03,
	GPIO_FFA_ALTIMETER_XCLR_N,
	GPIO_FFA_GPIO_EXP_05,
	GPIO_FFA_GPIO_EXP_06,
	GPIO_FFA_GPIO_EXP_07,
	GPIO_FFA_5V_BOOST_EN,
	GPIO_FFA_EXPANDER_IO09,
	GPIO_FFA_EXPANDER_IO10,
	GPIO_FFA_EXPANDER_IO11,
	GPIO_FFA_EXPANDER_IO12,
	GPIO_FFA_EXPANDER_IO13,
	GPIO_FFA_EXPANDER_IO14,
	GPIO_FFA_EXPANDER_IO15,
	/* Camera expander on FFA */
	GPIO_FFA_CAM_EXPANDER_BASE	= GPIO_FFA_EXPANDER_BASE + 16,
	GPIO_FFA_CAM_EXP_GPIO_00	= GPIO_FFA_CAM_EXPANDER_BASE,
	GPIO_FFA_CAM_EXP_GPIO_O1,
	GPIO_FFA_CAM_5MP_PWDN_VCM,
	GPIO_FFA_CAM_1MP_XCLR,
	GPIO_FFA_CAM_5MP_SHDN_N,
	GPIO_FFA_CAM_EXP_GPIO_05,
	GPIO_FFA_LED_DRV_EN1,
	GPIO_FFA_LED_DRV_EN2,
};

/* touch-screen macros */
#define TS_X_MIN		0
#define TS_X_MAX		240
#define TS_Y_MIN		0
#define TS_Y_MAX		320
#define TS_GPIO_I2C_SDA		17
#define TS_GPIO_I2C_SCL		4
#define TS_GPIO_IRQ		39
#define TS_I2C_SLAVE_ADDR	0x48	/* MELFAS Mcs8000(mms-128) addr is 0x48 */ 

#endif

