EXTRA_CFLAGS += -Iarch/arm/mach-msm

obj-$(CONFIG_MACH_MSM7X27A_M3) += board-m3.o
obj-$(CONFIG_MACH_MSM7X27A_M3) += board-m3-input.o
obj-$(CONFIG_MACH_MSM7X27A_M3) += board-m3-misc.o
obj-$(CONFIG_MACH_MSM7X27A_M3) += board-m3-mmc.o
obj-$(CONFIG_MACH_MSM7X27A_M3) += board-m3-sound.o

obj-$(CONFIG_MACH_LGE) += devices_lge.o
