EXTRA_CFLAGS += -Iarch/arm/mach-msm

obj-$(CONFIG_MACH_MSM7X27A_M3) += board-m3.o
obj-$(CONFIG_MACH_MSM7X27A_M3) += board-m3-input.o
obj-$(CONFIG_MACH_MSM7X27A_M3) += board-m3-misc.o
obj-$(CONFIG_MACH_MSM7X27A_M3) += board-m3-mmc.o
obj-$(CONFIG_MACH_MSM7X27A_M3) += board-m3-sound.o
obj-$(CONFIG_MACH_MSM7X27A_M3) += board-m3-panel.o
obj-$(CONFIG_MACH_MSM7X27A_M3) += board-m3-camera.o
obj-$(CONFIG_MACH_MSM7X27A_M3) += board-m3-pm.o
obj-$(CONFIG_MACH_MSM7X27A_M3) += board-m3-connectivity.o

obj-$(CONFIG_MACH_MSM7X27A_M3MPCS) += board-m3mpcs.o
obj-$(CONFIG_MACH_MSM7X27A_M3MPCS) += board-m3mpcs-input.o
obj-$(CONFIG_MACH_MSM7X27A_M3MPCS) += board-m3mpcs-misc.o
obj-$(CONFIG_MACH_MSM7X27A_M3MPCS) += board-m3mpcs-mmc.o
obj-$(CONFIG_MACH_MSM7X27A_M3MPCS) += board-m3mpcs-sound.o
obj-$(CONFIG_MACH_MSM7X27A_M3MPCS) += board-m3mpcs-panel.o
obj-$(CONFIG_MACH_MSM7X27A_M3MPCS) += board-m3mpcs-camera.o
obj-$(CONFIG_MACH_MSM7X27A_M3MPCS) += board-m3mpcs-pm.o

obj-$(CONFIG_MACH_MSM7X27A_HDK) += board-msm7x27a_hdk.o
obj-$(CONFIG_MACH_MSM7X27A_HDK) += board-msm7x27a_hdk-input.o
obj-$(CONFIG_MACH_MSM7X27A_HDK) += board-msm7x27a_hdk-misc.o
obj-$(CONFIG_MACH_MSM7X27A_HDK) += board-msm7x27a_hdk-mmc.o
obj-$(CONFIG_MACH_MSM7X27A_HDK) += board-msm7x27a_hdk-sound.o
obj-$(CONFIG_MACH_MSM7X27A_HDK) += board-msm7x27a_hdk-panel.o
obj-$(CONFIG_MACH_MSM7X27A_HDK) += board-msm7x27a_hdk-camera.o
obj-$(CONFIG_MACH_MSM7X27A_HDK) += board-msm7x27a_hdk-pm.o
obj-$(CONFIG_MACH_MSM7X27A_HDK) += lge_gpio_h2w.o
#ifndef CONFIG_ANDROID_VIBRATOR
obj-$(CONFIG_MACH_MSM7X27A_HDK) += pmic_vibrator.o
#endif
obj-$(CONFIG_MACH_LGE) += devices_lge.o
