# LGE_CHANGE
# NDIS driver is not used on E0 Tracfone model
# 2012-01-12 junghyun.cha@lge.com
ifeq (E0TRF, $(TARGET_CARRIER))
	EXTRA_CFLAGS += -DLGE_TRACFONE
endif

EXTRA_CFLAGS += -Iarch/arm/mach-msm
obj-$(CONFIG_LGE_PROC_COMM) += lge_proc_comm.o

obj-$(CONFIG_MACH_MSM7X25A_E1BR) += board-e1br.o
obj-$(CONFIG_MACH_MSM7X25A_E1BR) += board-e1br-input.o
obj-$(CONFIG_MACH_MSM7X25A_E1BR) += board-e1br-misc.o
obj-$(CONFIG_MACH_MSM7X25A_E1BR) += board-e1br-mmc.o
obj-$(CONFIG_MACH_MSM7X25A_E1BR) += board-e1br-sound.o
obj-$(CONFIG_MACH_MSM7X25A_E1BR) += board-e1br-panel.o
obj-$(CONFIG_MACH_MSM7X25A_E1BR) += board-e1br-camera.o
obj-$(CONFIG_MACH_MSM7X25A_E1BR) += board-e1br-pm.o
obj-$(CONFIG_MACH_MSM7X25A_E1BR) += board-e1br-usb.o
obj-$(CONFIG_MACH_MSM7X25A_E1BR) += board-e1br-connectivity.o

obj-$(CONFIG_MACH_MSM7X25A_E0EU) += board-e0eu.o
obj-$(CONFIG_MACH_MSM7X25A_E0EU) += board-e0eu-input.o
obj-$(CONFIG_MACH_MSM7X25A_E0EU) += board-e0eu-misc.o
obj-$(CONFIG_MACH_MSM7X25A_E0EU) += board-e0eu-mmc.o
obj-$(CONFIG_MACH_MSM7X25A_E0EU) += board-e0eu-sound.o
obj-$(CONFIG_MACH_MSM7X25A_E0EU) += board-e0eu-panel.o
obj-$(CONFIG_MACH_MSM7X25A_E0EU) += board-e0eu-camera.o
obj-$(CONFIG_MACH_MSM7X25A_E0EU) += board-e0eu-pm.o
obj-$(CONFIG_MACH_MSM7X25A_E0EU) += board-e0eu-usb.o
obj-$(CONFIG_MACH_MSM7X25A_E0EU) += board-e0eu-connectivity.o

obj-$(CONFIG_MACH_MSM7X27A_M3EU) += board-m3eu.o
obj-$(CONFIG_MACH_MSM7X27A_M3EU) += board-m3eu-input.o
obj-$(CONFIG_MACH_MSM7X27A_M3EU) += board-m3eu-misc.o
obj-$(CONFIG_MACH_MSM7X27A_M3EU) += board-m3eu-mmc.o
obj-$(CONFIG_MACH_MSM7X27A_M3EU) += board-m3eu-sound.o
obj-$(CONFIG_MACH_MSM7X27A_M3EU) += board-m3eu-panel.o
obj-$(CONFIG_MACH_MSM7X27A_M3EU) += board-m3eu-camera.o
obj-$(CONFIG_MACH_MSM7X27A_M3EU) += board-m3eu-pm.o
obj-$(CONFIG_MACH_MSM7X27A_M3EU) += board-m3eu-usb.o
obj-$(CONFIG_MACH_MSM7X27A_M3EU) += board-m3eu-connectivity.o

obj-$(CONFIG_MACH_MSM7X27A_M3MPCS) += board-m3mpcs.o
obj-$(CONFIG_MACH_MSM7X27A_M3MPCS) += board-m3mpcs-input.o
obj-$(CONFIG_MACH_MSM7X27A_M3MPCS) += board-m3mpcs-misc.o
obj-$(CONFIG_MACH_MSM7X27A_M3MPCS) += board-m3mpcs-mmc.o
obj-$(CONFIG_MACH_MSM7X27A_M3MPCS) += board-m3mpcs-sound.o
obj-$(CONFIG_MACH_MSM7X27A_M3MPCS) += board-m3mpcs-panel.o
obj-$(CONFIG_MACH_MSM7X27A_M3MPCS) += board-m3mpcs-camera.o
obj-$(CONFIG_MACH_MSM7X27A_M3MPCS) += board-m3mpcs-pm.o
obj-$(CONFIG_MACH_MSM7X27A_M3MPCS) += board-m3mpcs-usb.o
obj-$(CONFIG_MACH_MSM7X27A_M3MPCS) += board-m3mpcs-connectivity.o

obj-$(CONFIG_MACH_MSM7X25A_M3DOPEN) += board-m3dopen.o
obj-$(CONFIG_MACH_MSM7X25A_M3DOPEN) += board-m3dopen-input.o
obj-$(CONFIG_MACH_MSM7X25A_M3DOPEN) += board-m3dopen-misc.o
obj-$(CONFIG_MACH_MSM7X25A_M3DOPEN) += board-m3dopen-mmc.o
obj-$(CONFIG_MACH_MSM7X25A_M3DOPEN) += board-m3dopen-sound.o
obj-$(CONFIG_MACH_MSM7X25A_M3DOPEN) += board-m3dopen-panel.o
obj-$(CONFIG_MACH_MSM7X25A_M3DOPEN) += board-m3dopen-camera.o
obj-$(CONFIG_MACH_MSM7X25A_M3DOPEN) += board-m3dopen-pm.o
obj-$(CONFIG_MACH_MSM7X25A_M3DOPEN) += board-m3dopen-usb.o
obj-$(CONFIG_MACH_MSM7X25A_M3DOPEN) += board-m3dopen-connectivity.o

obj-$(CONFIG_MACH_MSM7X25A_M3DVIV) += board-m3dviv.o
obj-$(CONFIG_MACH_MSM7X25A_M3DVIV) += board-m3dviv-input.o
obj-$(CONFIG_MACH_MSM7X25A_M3DVIV) += board-m3dviv-misc.o
obj-$(CONFIG_MACH_MSM7X25A_M3DVIV) += board-m3dviv-mmc.o
obj-$(CONFIG_MACH_MSM7X25A_M3DVIV) += board-m3dviv-sound.o
obj-$(CONFIG_MACH_MSM7X25A_M3DVIV) += board-m3dviv-panel.o
obj-$(CONFIG_MACH_MSM7X25A_M3DVIV) += board-m3dviv-camera.o
obj-$(CONFIG_MACH_MSM7X25A_M3DVIV) += board-m3dviv-pm.o
obj-$(CONFIG_MACH_MSM7X25A_M3DVIV) += board-m3dviv-usb.o
obj-$(CONFIG_MACH_MSM7X25A_M3DVIV) += board-m3dviv-connectivity.o

obj-$(CONFIG_MACH_MSM7X27A_HDK) += board-msm7x27a_hdk.o
obj-$(CONFIG_MACH_MSM7X27A_HDK) += board-msm7x27a_hdk-input.o
obj-$(CONFIG_MACH_MSM7X27A_HDK) += board-msm7x27a_hdk-misc.o
obj-$(CONFIG_MACH_MSM7X27A_HDK) += board-msm7x27a_hdk-mmc.o
obj-$(CONFIG_MACH_MSM7X27A_HDK) += board-msm7x27a_hdk-sound.o
obj-$(CONFIG_MACH_MSM7X27A_HDK) += board-msm7x27a_hdk-panel.o
obj-$(CONFIG_MACH_MSM7X27A_HDK) += board-msm7x27a_hdk-camera.o
obj-$(CONFIG_MACH_MSM7X27A_HDK) += board-msm7x27a_hdk-pm.o
obj-$(CONFIG_MACH_MSM7X27A_HDK) += board-msm7x27a_hdk-usb.o
obj-$(CONFIG_MACH_MSM7X27A_HDK) += board-msm7x27a_hdk-connectivity.o
obj-$(CONFIG_MACH_MSM7X27A_HDK) += lge_gpio_h2w.o
#ifndef CONFIG_ANDROID_VIBRATOR
obj-$(CONFIG_MACH_MSM7X27A_HDK) += pmic_vibrator.o
#endif
obj-$(CONFIG_MACH_LGE) += devices_lge.o

obj-$(CONFIG_LGE_HANDLE_PANIC) += lge_handle_panic.o


