#
# Makefile for the sensor drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_SENSOR_GP2AP)	+= gp2ap002.o
obj-$(CONFIG_SENSOR_AK8975)	+= akm8975.o
obj-$(CONFIG_SENSOR_BMA222)	+= bma222.o 
obj-$(CONFIG_SENSOR_K3DH)       += k3dh.o
obj-$(CONFIG_SENSOR_AMI304)     += ami304.o
obj-$(CONFIG_SENSOR_AMI306)     += ami306.o
obj-$(CONFIG_SENSORS_BH1721)	+= bh1721fvc.o

